services:
  - type: web
    name: fochwebsite
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mysite.wsgi:application
    envVars:
      - key: DB_DRIVER
        sync: false
      - key: DB_SERVER
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false